### ISSUE TITLE
RHEL 7.6 image doesn't create a SWAP space.

### ISSUE THREAD

**Issue by prtyag** [linux-system-roles/experimental-azure-firstboot#14]
Here is the `free` command output on the RHEL 7.6 provisioned server.
`[root@sollabdsm35 ~]# free`
          `    total        used        free      shared  buff/cache   available`
`Mem:     4093067344    25631484  4066339644       30532     1096216  4064875684`
`Swap:             0           0           0`

**Comment by imcleod** [comment]
The latest images have been delivered with a fixed 2 GB swap partition.

**Comment by prtyag** [comment]
We have tested this using latest image and found swap space of 2GB. Hence closing this issue.
