### ISSUE TITLE
VLI: Firmware is expecting startup.nsh

### ISSUE THREAD

**Issue by prtyag** [linux-system-roles/experimental-azure-firstboot#15]
firmware is expecting startup.nsh to be added to EFI partition inside the image. The contents of this file need to be : fs0:path-of-efi-boot-loader .   As part of provisioning automation, we are planning to remove all manual steps, hence this is needed

**Comment by imcleod** [comment]
After a few typos on my part, I believe we have now provided an image that contains the correct startup.nsh content for Type II servers.

**Comment by prtyag** [comment]
Yes this issue has been fixed using latest image. so closing it.
